package com.kuzmichev.AdMetricsBot.constants;

public enum CallBackEnum {
    ADD_YANDEX_CALLBACK,
    ADD_VK_CALLBACK,
    ADD_MYTARGET_CALLBACK,
    ADD_BITRIX_CALLBACK,
    ADD_AMOCRM_CALLBACK,
    ADD_YCLIENTS_CALLBACK,
    EDIT_TIMEZONE_CALLBACK,
    EDIT_TIMEZONE_MANUAL_CALLBACK,
    EDIT_LANGUAGE_CALLBACK,
    TEST_MESSAGE_CALLBACK,
    NO_CONTINUE_CALLBACK,
    EDIT_TIMER_CALLBACK,
    ADD_TOKENS_CALLBACK,
    DELETE_USER_STEP_1_CALLBACK,
    DELETE_USER_STEP_2_CALLBACK,
    START_REGISTRATION_CALLBACK,
    YES_ADD_CALLBACK,
    ENABLE_NOTIFICATIONS_CALLBACK,
    DISABLE_NOTIFICATIONS_CALLBACK,
    NOT_DELETE_USER_CALLBACK,
    SETTINGS_EXIT_CALLBACK,
    SETTINGS_BACK_CALLBACK,
    PROJECT_CREATE_CALLBACK,
    PROJECT_EDIT_CALLBACK,
    PROJECT_CREATE_ASK_NAME_CALLBACK,
    PROJECTS_CALLBACK,
    TEST_YANDEX_CALLBACK,
    ;
//
//    private final String callBackName;
//    CallBackEnum(String callBackName) {
//        this.callBackName = callBackName;
//    }
//    public String getCallBackName() {
//        return callBackName;
//    }

}
