package com.kuzmichev.AdMetricsBot.constants;

public enum StateEnum {
    SETTINGS_STATE("SETTINGS_STATE"),
        SETTINGS_PROJECTS_STATE("SETTINGS_PROJECTS_STATE"),
            SETTINGS_PROJECT_CREATE_STATE("SETTINGS_PROJECT_CREATE_STATE"),
                SETTINGS_PROJECT_CREATE_ASK_NAME_STATE("SETTINGS_PROJECT_CREATE_ASK_NAME_STATE"),

            SETTINGS_ADD_INPUTS_STATE("SETTINGS_ADD_INPUTS_STATE"),
                SETTINGS_ADD_YANDEX_STATE("SETTINGS_ADD_YANDEX_STATE"),
                    SETTINGS_ADD_YANDEX_TEST_STATE("SETTINGS_ADD_YANDEX_TEST_STATE"),
                SETTINGS_ADD_VK_STATE("SETTINGS_ADD_VK_STATE"),
                SETTINGS_ADD_MYTARGET_STATE("SETTINGS_ADD_MYTARGET_STATE"),
                SETTINGS_ADD_BITRIX_STATE("SETTINGS_ADD_BITRIX_STATE"),
                SETTINGS_ADD_AMOCRM_STATE("SETTINGS_ADD_AMOCRM_STATE"),
                SETTINGS_ADD_YCLIENTS_STATE("SETTINGS_ADD_YCLIENTS_STATE"),

        SETTINGS_EDIT_TIMER_STATE("SETTINGS_EDIT_TIMER_STATE"),

        SETTINGS_EDIT_TIMEZONE_STATE("SETTINGS_EDIT_TIMEZONE_STATE"),
            SETTINGS_EDIT_TIMEZONE_MANUAL_STATE("SETTINGS_EDIT_TIMEZONE_MANUAL_STATE"),
                SETTINGS_EDIT_TIMEZONE_COMPLETE_STATE("SETTINGS_EDIT_TIMEZONE_COMPLETE_STATE"),



    // Универсальные
    WORKING_STATE("WORKING_STATE"),



    REGISTRATION("REGISTRATION"),
    REGISTRATION_STATE("REGISTRATION_STATE"),

    REGISTRATION_EDIT_TIMEZONE_STATE("REGISTRATION_EDIT_TIMEZONE_STATE"),
        REGISTRATION_EDIT_TIMEZONE_MANUAL_STATE("REGISTRATION_EDIT_TIMEZONE_MANUAL_STATE"),
            REGISTRATION_EDIT_TIMEZONE_COMPLETE_STATE("REGISTRATION_EDIT_TIMEZONE_COMPLETE_STATE"),

    REGISTRATION_PROJECT_CREATE_ASK_NAME_STATE("REGISTRATION_PROJECT_CREATE_ASK_NAME_STATE"),

        REGISTRATION_ADD_INPUTS_STATE("REGISTRATION_ADD_INPUTS_STATE"),
            REGISTRATION_ADD_YANDEX_STATE("REGISTRATION_ADD_YANDEX_STATE"),
                REGISTRATION_ADD_YANDEX_TEST_STATE("REGISTRATION_ADD_YANDEX_TEST_STATE"),
            REGISTRATION_ADD_BITRIX_STATE("REGISTRATION_ADD_BITRIX_STATE"),
            REGISTRATION_ADD_YCLIENTS_STATE("REGISTRATION_ADD_YCLIENTS_STATE"),

    REGISTRATION_EDIT_TIMER_STATE("REGISTRATION_EDIT_TIMER_STATE"),







    ;

    private final String stateName;

    StateEnum(String stateName) {
        this.stateName = stateName;
    }

    public String getStateName() {
        return stateName;
    }

}
